### ISSUE TITLE
Fix crate warnings

### ISSUE THREAD

**Issue by Xindage** [Xindage/All-out-War-2.3#24]
Some crates give 2 warning at once, if possible we should decrease it to 1 line, see this example:
![image](https://user-images.githubusercontent.com/6380147/209443476-61b35713-f9b6-4ac6-82d9-4643167e29c2.png)
this can be reduced to like:
Xindage from blue team got the quad shotgun!

**Comment by Xindage** [comment]
I have this on progress now.

**Comment by Igor369pl** [comment]
It is a small QoL but can you add short distinct sound effects to accompany global warnings? E.g. do not play any sound during disarm crate but play something when enemy spawns a juggernaut.

**Comment by Xindage** [comment]
seems like a good idea.

**Comment by Xindage** [comment]
what about one of these:
https://freesound.org/people/thisusernameis/sounds/426888/
https://freesound.org/people/Eponn/sounds/528863/
https://freesound.org/people/Vladimir_WN/sounds/581292/

**Comment by Igor369pl** [comment]
Can not go wrong with beeps lol. The highest priority warning could use this https://freesound.org/people/bumpelsnake/sounds/456566/
